microservice:
  image:
    repository: ghcr.io/apasteau/opentelemetry-hands-on/order
    tag: "latest"
  environment:
    KAFKA_BROKERS: kafka-cluster:9092
    CART_SVC_URL: http://shopping-cart:8080
